# This file was *autogenerated* from the file types.sage
from sage.all_cmdline import *   # import sage library

from sage.all import *

PRIME = 65537
F = GF(PRIME)
Polynomial = PolynomialRing(F, 'X')

